# Generated by Django 5.0.4 on 2026-07-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Sarlavha')),
                ('file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video fayl')),
                ('telegram_file_id', models.CharField(blank=True, help_text="Bo'sh qoldiring — bot birinchi yuborishda avtomatik to'ldiradi.", max_length=512, verbose_name='Telegram file_id (avtomatik)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='producttutorialstep',
            options={'ordering': ['order'], 'verbose_name': 'Kontent (mahsulot-video)', 'verbose_name_plural': 'Kontent (mahsulot-video)'},
        ),
        migrations.RemoveField(
            model_name='producttutorialstep',
            name='video_file_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='button_label',
            field=models.CharField(max_length=64, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='intro_text',
            field=models.TextField(verbose_name='Video oldidan matn'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_steps', to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='protect_content',
            field=models.BooleanField(default=True, verbose_name='Himoyalash (ulashish/saqlashni taqiqlash)'),
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorial_steps', to='products.video', verbose_name='Video'),
        ),
    ]
