# Generated by Django 5.0.4 on 2026-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_video_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttutorialstep',
            name='video',
        ),
        migrations.AlterModelOptions(
            name='producttutorialstep',
            options={'ordering': ['order'], 'verbose_name': "Qo'llanma qadami", 'verbose_name_plural': "Qo'llanma qadamlari"},
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video yuklang. Yuklamasangiz bot «tez orada» deb yozadi.', null=True, upload_to='videos/', verbose_name='Video (ixtiyoriy)'),
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='video_file_id',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Rasm (ixtiyoriy)'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='button_label',
            field=models.CharField(help_text="Botda ko'rinadigan tugma, masalan: «1-qadam: Tozalash».", max_length=64, verbose_name='Tugma matni'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='intro_text',
            field=models.TextField(help_text="Video yuborilishidan oldin ko'rsatiladigan qisqa izoh.", verbose_name='Video oldidan matn'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Tugmalar tartibi: 1, 2, 3 ... (kichik raqam yuqorida turadi).', verbose_name='Ketma-ketlik'),
        ),
        migrations.AlterField(
            model_name='producttutorialstep',
            name='protect_content',
            field=models.BooleanField(default=True, verbose_name='Himoya (ulashish/saqlashni taqiqlash)'),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
