# Generated by Django 5.0.4 on 2026-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_producttutorialstep_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopProduct',
            fields=[
            ],
            options={
                'verbose_name': 'Top mahsulot',
                'verbose_name_plural': 'Bu oydagi top mahsulotlar',
                'ordering': ['top_order', 'name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='Tavsif (inglizcha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='Tavsif (ruscha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_top',
            field=models.BooleanField(db_index=True, default=False, help_text="Belgilansa, botdagi «Bu oydagi top mahsulotlar» ro'yxatida chiqadi.", verbose_name='Bu oyning top mahsuloti'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(blank=True, max_length=256, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ru',
            field=models.CharField(blank=True, max_length=256, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_note',
            field=models.CharField(blank=True, help_text="Ixtiyoriy: «Eng ko'p sotilgan», «Yangi kelgan» kabi qisqa yozuv. Mahsulot ostida ko'rinadi.", max_length=200, verbose_name='Top izohi'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_note_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Top izohi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_note_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Top izohi (ruscha)'),
        ),
        migrations.AddField(
            model_name='product',
            name='top_order',
            field=models.PositiveSmallIntegerField(default=1, help_text="1 — birinchi bo'lib chiqadi, keyin 2, 3 ...", verbose_name="Top ro'yxatdagi o'rni"),
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='button_label_en',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tugma matni (inglizcha)'),
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='button_label_ru',
            field=models.CharField(blank=True, max_length=64, verbose_name='Tugma matni (ruscha)'),
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='intro_text_en',
            field=models.TextField(blank=True, verbose_name='Video oldidan matn (inglizcha)'),
        ),
        migrations.AddField(
            model_name='producttutorialstep',
            name='intro_text_ru',
            field=models.TextField(blank=True, verbose_name='Video oldidan matn (ruscha)'),
        ),
    ]
