# Generated by Django 5.0.4 on 2026-07-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_topproduct_product_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.PositiveIntegerField(default=0, verbose_name="Hozirgi narxi (so'm)"),
        ),
        migrations.AddField(
            model_name='product',
            name='old_price',
            field=models.PositiveIntegerField(blank=True, help_text="Chegirmani ko'rsatish uchun. Bo'sh qoldirsangiz chegirma ko'rsatilmaydi.", null=True, verbose_name="Eski narxi (so'm)"),
        ),
    ]
