# Generated by Django 5.0.4 on 2026-07-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttutorialstep',
            name='intro_text',
            field=models.TextField(blank=True, help_text="Ixtiyoriy: video yuborilishidan oldin ko'rsatiladigan qisqa izoh. Bo'sh qoldirsangiz — faqat video yuboriladi.", verbose_name='Video oldidan matn'),
        ),
    ]
