# Generated by Django 5.0.4 on 2026-07-27 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_producttutorialstep_intro_text'),
        ('users', '0014_backfill_registered_at_and_seller_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=256, verbose_name='Ism-familiya')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Telefon')),
                ('delivery_method', models.CharField(choices=[('yandex', "🚕 Yandeks (Toshkent bo'ylab)"), ('bts', '📦 BTS (viloyatlarga)')], max_length=16, verbose_name='Yetkazish')),
                ('address', models.TextField(help_text="Yandeks: ko'cha va uy. BTS: viloyat, shahar va filial.", verbose_name='Manzil')),
                ('comment', models.TextField(blank=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('new', '🆕 Yangi'), ('confirmed', '☎️ Tasdiqlangan'), ('shipped', "🚚 Yo'lda"), ('delivered', '✅ Yetkazildi'), ('cancelled', '❌ Bekor qilingan')], db_index=True, default='new', max_length=16, verbose_name='Holat')),
                ('total', models.PositiveBigIntegerField(default=0, verbose_name="Jami (so'm)")),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256, verbose_name='Nomi')),
                ('price', models.PositiveBigIntegerField(verbose_name="Narxi (so'm)")),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma qatori',
                'verbose_name_plural': 'Buyurtma qatorlari',
            },
        ),
    ]
