# Generated by Django 5.0.4 on 2026-07-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_seller_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="To'langan vaqt"),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', '💵 Yetkazishda naqd'), ('online', '💳 Karta orqali (online)')], default='cod', max_length=16, verbose_name="To'lov turi"),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('pending', "To'lov kutilmoqda"), ('paid', "✅ To'langan")], db_index=True, default='unpaid', max_length=16, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='order',
            name='provider_charge_id',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name="To'lov ID"),
        ),
    ]
