# Generated by Django 5.0.4 on 2026-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_paid_at_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveBigIntegerField(default=0, verbose_name="Yetkazish haqi (so'm)"),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
    ]
