# Generated by Django 5.0.4 on 2026-07-28 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_fee_order_latitude_order_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reminded_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Eslatma yuborilgan'),
        ),
    ]
