# Generated by Django 5.0.4 on 2026-07-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome after registration'), ('product_intro', 'Product tutorial intro'), ('week1_checkin', 'Week 1 check-in'), ('week2_progress', 'Week 2 progress request'), ('birthday_sale', 'Birthday sale'), ('feedback_thanks', 'After feedback thank-you')], max_length=32)),
                ('body', models.TextField(help_text='Supports {{ variable }} placeholders. Use Telegram HTML markup.')),
                ('parse_mode', models.CharField(choices=[('HTML', 'HTML'), ('Markdown', 'Markdown')], default='HTML', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message template',
                'verbose_name_plural': 'Message templates',
            },
        ),
        migrations.CreateModel(
            name='CampaignLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=True)),
                ('error_detail', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.messagetemplate')),
            ],
            options={
                'verbose_name': 'Campaign log',
                'verbose_name_plural': 'Campaign logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
