# Generated by Django 5.0.4 on 2026-07-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('users', '0004_fix_group_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Kampaniya jurnali', 'verbose_name_plural': 'Kampaniya jurnallari'},
        ),
        migrations.AlterModelOptions(
            name='messagetemplate',
            options={'verbose_name': 'Xabar shabloni', 'verbose_name_plural': 'Xabar shablonlari'},
        ),
        migrations.AlterField(
            model_name='campaignlog',
            name='error_detail',
            field=models.TextField(blank=True, verbose_name='Xato tafsiloti'),
        ),
        migrations.AlterField(
            model_name='campaignlog',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='campaignlog',
            name='success',
            field=models.BooleanField(default=True, verbose_name='Muvaffaqiyatli'),
        ),
        migrations.AlterField(
            model_name='campaignlog',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.messagetemplate', verbose_name='Shablon'),
        ),
        migrations.AlterField(
            model_name='campaignlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text="{{ o'zgaruvchi }} qo'llab-quvvatlanadi. Masalan: {{ user.full_name }}, {{ product.name }}, {{ discount }}. Telegram HTML formatidan foydalaning.", verbose_name='Xabar matni'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='parse_mode',
            field=models.CharField(choices=[('HTML', 'HTML'), ('Markdown', 'Markdown')], default='HTML', max_length=8, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='template_type',
            field=models.CharField(choices=[('welcome', "Ro'yxatdan o'tgach salomlashish"), ('product_intro', "Mahsulot qo'llanmasi kirish"), ('week1_checkin', "1-hafta so'rovi"), ('week2_progress', "2-hafta natija so'rovi"), ('birthday_sale', "Tug'ilgan kun chegirmasi"), ('feedback_thanks', 'Fikr uchun rahmat')], max_length=32, verbose_name='Shablon turi'),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan'),
        ),
    ]
