# Generated by Django 5.0.4 on 2026-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaignlog_options_and_more'),
        ('users', '0006_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['-sent_at'], name='campaigns_c_sent_at_239ab4_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignlog',
            index=models.Index(fields=['user', '-sent_at'], name='campaigns_c_user_id_17a6e3_idx'),
        ),
    ]
