# Generated by Django 5.0.4 on 2026-07-17 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_seed_default_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignlog',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Yuborilgan xabar', 'verbose_name_plural': 'Yuborilgan xabarlar'},
        ),
    ]
