# Generated by Django 5.0.4 on 2026-07-20 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_unique_template_type'),
        ('products', '0003_remove_producttutorialstep_video_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Ro'yxatda ko'rinadi. Mijozga yuborilmaydi.", max_length=128, verbose_name='Sarlavha (faqat siz uchun)')),
                ('body', models.TextField(help_text="Mijozga boradigan matn. Telegram HTML: <b>qalin</b>, <i>qiya</i>, <a href='...'>havola</a>.", verbose_name='Xabar matni')),
                ('photo', models.ImageField(blank=True, help_text='Yuklasangiz, xabar rasm bilan boradi.', null=True, upload_to='broadcasts/', verbose_name='Rasm (ixtiyoriy)')),
                ('audience', models.CharField(choices=[('all', 'Hamma (botga ulangan barcha xaridorlar)'), ('by_skin', "Teri turi bo'yicha"), ('by_product', 'Mahsulot sotib olganlar')], default='all', max_length=16, verbose_name='Kimlarga')),
                ('skin_condition', models.CharField(blank=True, help_text="«Teri turi bo'yicha» tanlansagina ishlaydi.", max_length=20, verbose_name='Teri turi')),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('sending', 'Yuborilmoqda'), ('sent', 'Yuborildi'), ('failed', 'Xato')], default='draft', editable=False, max_length=12, verbose_name='Holat')),
                ('total', models.PositiveIntegerField(default=0, editable=False, verbose_name='Jami')),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Yuborildi')),
                ('failed_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Yetmadi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='«Mahsulot sotib olganlar» tanlansagina ishlaydi.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
    ]
