# Generated by Django 5.0.4 on 2026-07-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_broadcast'),
        ('users', '0013_telegramuser_language_telegramuser_registered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='body_en',
            field=models.TextField(blank=True, verbose_name='Xabar matni (inglizcha)'),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='body_ru',
            field=models.TextField(blank=True, verbose_name='Xabar matni (ruscha)'),
        ),
        migrations.CreateModel(
            name='AutoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Faqat siz uchun. Masalan: «1 hafta — keshbek taklifi».', max_length=128, verbose_name='Nomi')),
                ('trigger', models.CharField(choices=[('after_purchase', 'Mahsulot sotib olingandan keyin'), ('after_registration', "Ro'yxatdan o'tgandan keyin")], default='after_purchase', max_length=24, verbose_name='Qachondan hisoblanadi')),
                ('delay_value', models.PositiveSmallIntegerField(default=7, help_text='Raqam. Masalan: 7.', verbose_name='Qancha vaqtdan keyin')),
                ('delay_unit', models.CharField(choices=[('minute', 'daqiqa'), ('hour', 'soat'), ('day', 'kun')], default='day', help_text='«daqiqa» — sinash uchun qulay, «kun» — haqiqiy ish uchun.', max_length=8, verbose_name='Vaqt birligi')),
                ('body', models.TextField(help_text='Mijozga boradigan matn. {{ user.full_name }} va {{ product.name }} ishlaydi. Telegram HTML: <b>qalin</b>, <i>qiya</i>.', verbose_name='Xabar matni')),
                ('body_ru', models.TextField(blank=True, verbose_name='Xabar matni (ruscha)')),
                ('body_en', models.TextField(blank=True, verbose_name='Xabar matni (inglizcha)')),
                ('button_action', models.CharField(choices=[('none', 'Tugmasiz (faqat matn)'), ('feedback', '«Fikr bildirish» tugmasi'), ('progress', '«Rasm yuborish» tugmasi'), ('discounts', "«Chegirmalarni ko'rish» tugmasi")], default='none', max_length=16, verbose_name='Xabar ostidagi tugma')),
                ('button_label', models.CharField(blank=True, help_text="«Tugmasiz» tanlansa, bu maydon e'tiborga olinmaydi.", max_length=64, verbose_name='Tugma matni')),
                ('button_label_ru', models.CharField(blank=True, max_length=64, verbose_name='Tugma matni (ruscha)')),
                ('button_label_en', models.CharField(blank=True, max_length=64, verbose_name='Tugma matni (inglizcha)')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa bot bu xabarni umuman yubormaydi.", verbose_name='Yoqilgan')),
                ('is_test_mode', models.BooleanField(default=False, help_text="Yoqilsa xabar FAQAT quyida tanlangan mijozga boradi. Vaqtni «1 daqiqa» qilib sinab ko'rish uchun.", verbose_name='Sinov rejimi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('test_user', models.ForeignKey(blank=True, help_text='Sinov rejimida xabar shu mijozga yuboriladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.telegramuser', verbose_name='Sinov mijozi')),
            ],
            options={
                'verbose_name': 'Avtomatik xabar',
                'verbose_name_plural': 'Avtomatik xabarlar',
                'ordering': ['trigger', 'delay_value'],
            },
        ),
        migrations.CreateModel(
            name='AutoMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(editable=False, max_length=32)),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('success', models.BooleanField(default=True, verbose_name='Yetkazildi')),
                ('error_detail', models.TextField(blank=True, verbose_name='Xato')),
                ('auto_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.automessage', verbose_name='Avtomatik xabar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Avtomatik xabar jurnali',
                'verbose_name_plural': 'Avtomatik xabarlar jurnali',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['-sent_at'], name='campaigns_a_sent_at_d5449e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='automessagelog',
            constraint=models.UniqueConstraint(fields=('auto_message', 'anchor'), name='uniq_automessage_anchor'),
        ),
    ]
