# Generated by Django 5.0.4 on 2026-07-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_retire_progress_button_action'),
        ('users', '0014_backfill_registered_at_and_seller_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Faqat siz uchun. Masalan: «Har 2 haftada — qayta buyurtma».', max_length=128, verbose_name='Nomi')),
                ('body', models.TextField(help_text='{{ user.full_name }} ishlaydi. Telegram HTML.', verbose_name='Xabar matni')),
                ('interval_days', models.PositiveSmallIntegerField(default=14, verbose_name='Necha kunda bir marta')),
                ('next_run_at', models.DateTimeField(verbose_name='Keyingi yuborilish vaqti')),
                ('last_sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Oxirgi yuborilgan')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yoqilgan')),
                ('send_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Yuborilgan marta')),
                ('error_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Xatolar soni')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.ForeignKey(help_text='Faqat botga ulangan (telegram_id bor) mijozlarga yuboriladi.', on_delete=django.db.models.deletion.CASCADE, related_name='reminder_rules', to='users.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Takrorlanuvchi eslatma',
                'verbose_name_plural': 'Takrorlanuvchi eslatmalar',
                'ordering': ['next_run_at'],
            },
        ),
    ]
