# Generated by Django 5.0.4 on 2026-07-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_telegramuser_language_telegramuser_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, help_text="O'chirilsa botdagi «Bonuslarim» bo'limi ko'rinmaydi va ball yig'ilmaydi.", verbose_name='Bonus dasturi yoqilgan')),
                ('points_registration', models.PositiveSmallIntegerField(default=50, help_text="Mijoz botda ro'yxatdan o'tishni tugatganda beriladi.", verbose_name="Ro'yxatdan o'tgani uchun")),
                ('points_purchase', models.PositiveSmallIntegerField(default=100, help_text='Mijozga mahsulot biriktirilganda beriladi.', verbose_name='Har bir xarid uchun')),
                ('points_feedback', models.PositiveSmallIntegerField(default=30, verbose_name='Mahsulotga baho bergani uchun')),
                ('points_progress', models.PositiveSmallIntegerField(default=50, verbose_name='Oldin/keyin rasmi uchun')),
                ('points_referral', models.PositiveSmallIntegerField(default=150, help_text="Taklif qilingan do'st ro'yxatdan o'tib bo'lgach beriladi.", verbose_name="Do'stini taklif qilgani uchun")),
                ('points_birthday', models.PositiveSmallIntegerField(default=200, verbose_name="Tug'ilgan kun sovg'asi")),
                ('points_quiz', models.PositiveSmallIntegerField(default=20, verbose_name='Teri testini topshirgani uchun')),
                ('bronze_cashback', models.PositiveSmallIntegerField(default=3, verbose_name='Bronza keshbek (%)')),
                ('silver_from', models.PositiveIntegerField(default=1000, verbose_name='Kumush darajasi (balldan)')),
                ('silver_cashback', models.PositiveSmallIntegerField(default=5, verbose_name='Kumush keshbek (%)')),
                ('gold_from', models.PositiveIntegerField(default=3000, verbose_name='Oltin darajasi (balldan)')),
                ('gold_cashback', models.PositiveSmallIntegerField(default=7, verbose_name='Oltin keshbek (%)')),
                ('platinum_from', models.PositiveIntegerField(default=7000, verbose_name='Platina darajasi (balldan)')),
                ('platinum_cashback', models.PositiveSmallIntegerField(default=10, verbose_name='Platina keshbek (%)')),
            ],
            options={
                'verbose_name': 'Bonus dasturi sozlamalari',
                'verbose_name_plural': 'Bonus dasturi sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Nomi')),
                ('title_ru', models.CharField(blank=True, max_length=128, verbose_name='Nomi (ruscha)')),
                ('title_en', models.CharField(blank=True, max_length=128, verbose_name='Nomi (inglizcha)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('description_ru', models.TextField(blank=True, verbose_name='Tavsif (ruscha)')),
                ('description_en', models.TextField(blank=True, verbose_name='Tavsif (inglizcha)')),
                ('cost_points', models.PositiveIntegerField(default=500, verbose_name='Narxi (ball)')),
                ('code_prefix', models.CharField(default='RB', help_text="Har bir mijozga RB-XXXXXX ko'rinishida noyob kod beriladi.", max_length=12, verbose_name='Promokod boshlanishi')),
                ('stock', models.PositiveIntegerField(blank=True, help_text="Bo'sh qoldirsangiz — cheklanmagan.", null=True, verbose_name='Nechta qoldi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Sovg'a",
                'verbose_name_plural': "Sovg'alar (ballga almashtiriladi)",
                'ordering': ['cost_points'],
            },
        ),
        migrations.CreateModel(
            name='LoyaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0, verbose_name='Ball balansi')),
                ('lifetime_points', models.PositiveIntegerField(default=0, verbose_name="Jami yig'ilgan ball")),
                ('tier', models.CharField(choices=[('bronze', 'Bronza'), ('silver', 'Kumush'), ('gold', 'Oltin'), ('platinum', 'Platina')], default='bronze', max_length=12, verbose_name='Daraja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty', to='users.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Bonus hisobi',
                'verbose_name_plural': 'Bonus hisoblari',
                'ordering': ['-lifetime_points'],
            },
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Promokod')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Sarflangan ball')),
                ('is_used', models.BooleanField(default=False, help_text="Mijoz do'konda kodni ishlatgach belgilang.", verbose_name='Ishlatilgan')),
                ('used_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olingan vaqt')),
                ('reward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='loyalty.reward', verbose_name="Sovg'a")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='users.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': "Almashtirilgan sovg'a",
                'verbose_name_plural': "Almashtirilgan sovg'alar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(help_text="Musbat — qo'shiladi, manfiy — ayiriladi.", verbose_name='Ball')),
                ('reason', models.CharField(choices=[('registration', "Ro'yxatdan o'tish"), ('purchase', 'Xarid'), ('feedback', 'Mahsulotga baho'), ('progress', 'Natija rasmi'), ('referral', "Do'st taklifi"), ('birthday', "Tug'ilgan kun"), ('quiz', 'Teri testi'), ('redeem', "Sovg'aga almashtirildi"), ('manual', 'Admin tuzatishi')], max_length=16, verbose_name='Sabab')),
                ('reference', models.CharField(blank=True, editable=False, max_length=64)),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to='users.telegramuser', verbose_name='Mijoz')),
            ],
            options={
                'verbose_name': 'Ball harakati',
                'verbose_name_plural': 'Ball harakatlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='loyalty_poi_user_id_eeff9c_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pointstransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('user', 'reason', 'reference'), name='uniq_points_reference'),
        ),
    ]
