# Generated by Django 5.0.4 on 2026-07-23 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyalty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltysettings',
            name='bronze_cashback',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Bronza keshbek / chegirma (%)'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='gold_cashback',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Oltin keshbek / chegirma (%)'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='platinum_cashback',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Platina keshbek / chegirma (%)'),
        ),
        migrations.AlterField(
            model_name='loyaltysettings',
            name='silver_cashback',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Kumush keshbek / chegirma (%)'),
        ),
    ]
