# Generated by Django 5.0.4 on 2026-07-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday_discount_percent', models.PositiveSmallIntegerField(default=30)),
                ('week1_delay_days', models.PositiveSmallIntegerField(default=7)),
                ('week2_delay_days', models.PositiveSmallIntegerField(default=14)),
                ('feedback_button_label', models.CharField(default='Leave feedback', max_length=64)),
                ('before_after_button_label', models.CharField(default='Send my photos', max_length=64)),
            ],
            options={
                'verbose_name': 'Global settings',
                'verbose_name_plural': 'Global settings',
            },
        ),
    ]
