# Generated by Django 5.0.4 on 2026-07-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Sarlavha')),
                ('percent', models.PositiveSmallIntegerField(default=0, verbose_name='Chegirma foizi (%)')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('promo_code', models.CharField(blank=True, max_length=64, verbose_name='Promokod')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='globalsettings',
            options={'verbose_name': 'Umumiy sozlamalar', 'verbose_name_plural': 'Umumiy sozlamalar'},
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='before_after_button_label',
            field=models.CharField(default='Rasmlarni yuborish', max_length=64, verbose_name='Rasm tugmasi matni'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='birthday_discount_percent',
            field=models.PositiveSmallIntegerField(default=30, verbose_name="Tug'ilgan kun chegirmasi (%)"),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='feedback_button_label',
            field=models.CharField(default='Fikr bildirish', max_length=64, verbose_name='Fikr tugmasi matni'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='week1_delay_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='1-hafta kechikishi (kun)'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='week2_delay_days',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='2-hafta kechikishi (kun)'),
        ),
    ]
