# Generated by Django 5.0.4 on 2026-07-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0002_discount_alter_globalsettings_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='before_after_button_label',
            field=models.CharField(default='Rasmlarni yuborish', help_text="Natija rasmi so'rash xabari ostidagi tugma matni.", max_length=64, verbose_name='Rasm tugmasi matni'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='birthday_discount_percent',
            field=models.PositiveSmallIntegerField(default=30, help_text="Tug'ilgan kun xabaridagi foiz. Xabar matnida {{ discount }} o'rniga shu raqam qo'yiladi.", verbose_name="Tug'ilgan kun chegirmasi (%)"),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='feedback_button_label',
            field=models.CharField(default='Fikr bildirish', help_text="Fikr so'rash xabari ostidagi tugmada shu matn chiqadi.", max_length=64, verbose_name='Fikr tugmasi matni'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='week1_delay_days',
            field=models.PositiveSmallIntegerField(default=7, help_text="Mahsulot sotib olingandan necha kun keyin bot mijozdan fikr so'rasin. Odatda 7.", verbose_name="Fikr so'rash muddati (kun)"),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='week2_delay_days',
            field=models.PositiveSmallIntegerField(default=14, help_text="Mahsulot sotib olingandan necha kun keyin bot «oldin/keyin» rasmlarini so'rasin. Odatda 14.", verbose_name="Natija rasmi so'rash muddati (kun)"),
        ),
    ]
