# Generated by Django 5.0.4 on 2026-07-23 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0003_alter_globalsettings_before_after_button_label_and_more'),
        # These columns are the source the seed migration copies from — drop
        # them first and the new AutoMessage rows come out with default
        # delays and English button labels instead of the shop's own.
        ('campaigns', '0010_seed_auto_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalsettings',
            name='before_after_button_label',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='feedback_button_label',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='week1_delay_days',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='week2_delay_days',
        ),
    ]
