# Generated by Django 5.0.4 on 2026-07-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0004_remove_globalsettings_before_after_button_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/realbeauty_uz', verbose_name='Instagram havolasi'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='shop_name',
            field=models.CharField(default='Real Beauty', help_text="Mini App sarlavhasida ko'rinadi.", max_length=64, verbose_name="Do'kon nomi"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='shop_tagline',
            field=models.CharField(blank=True, default="Teringizga professional g'amxo'rlik", max_length=120, verbose_name="Do'kon shiori"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram kanal havolasi'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='youtube_url',
            field=models.URLField(blank=True, verbose_name='YouTube havolasi'),
        ),
    ]
