# Generated by Django 5.0.4 on 2026-07-27 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_settings', '0005_globalsettings_instagram_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='delivery_fee_bts',
            field=models.PositiveIntegerField(default=35000, help_text="Viloyatlarga pochta. Savatchada alohida qator bo'lib qo'shiladi.", verbose_name="BTS yetkazish haqi (so'm)"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='delivery_fee_yandex',
            field=models.PositiveIntegerField(default=25000, help_text="Toshkent bo'ylab. Savatchada alohida qator bo'lib qo'shiladi.", verbose_name="Yandeks yetkazish haqi (so'm)"),
        ),
    ]
