# Generated by Django 5.0.4 on 2026-07-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True)),
                ('full_name', models.CharField(max_length=256)),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('face_condition', models.CharField(choices=[('dry', 'Dry'), ('oily', 'Oily'), ('combined', 'Combined'), ('normal', 'Normal'), ('sensitive', 'Sensitive')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('source', models.CharField(choices=[('self', 'Self-registered'), ('admin', 'Admin-assisted')], default='self', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Telegram user',
                'verbose_name_plural': 'Telegram users',
            },
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('week1_sent', models.BooleanField(default=False)),
                ('week2_sent', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'User product',
                'verbose_name_plural': 'User products',
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='products',
            field=models.ManyToManyField(blank=True, through='users.UserProduct', to='products.product'),
        ),
    ]
