# Generated by Django 5.0.4 on 2026-07-13 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Telegram foydalanuvchi', 'verbose_name_plural': 'Telegram foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='userproduct',
            options={'verbose_name': 'Foydalanuvchi mahsuloti', 'verbose_name_plural': 'Foydalanuvchi mahsulotlari'},
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='registration_status',
            field=models.CharField(choices=[('pending', "To'ldirilishi kerak"), ('completed', "To'ldirilgan")], default='pending', max_length=12, verbose_name="Ro'yxat holati"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='face_condition',
            field=models.CharField(blank=True, choices=[('dry', 'Quruq'), ('oily', "Yog'li"), ('combined', 'Aralash'), ('normal', 'Normal'), ('sensitive', 'Sezgir')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='source',
            field=models.CharField(choices=[('self', "O'zi ro'yxatdan o'tgan"), ('admin', 'Admin yordamida')], default='self', max_length=10),
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, help_text='Sotuvchining Telegram ID raqami (referal havola uchun).', unique=True)),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sotuvchi profili',
                'verbose_name_plural': 'Sotuvchilar profili',
            },
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='referred_by_seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to='users.sellerprofile', verbose_name='Referal sotuvchi'),
        ),
    ]
