# Generated by Django 5.0.4 on 2026-07-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_video_alter_product_options_and_more'),
        ('users', '0004_fix_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='face_condition',
            field=models.CharField(blank=True, choices=[('dry', 'Quruq'), ('oily', "Yog'li"), ('combined', 'Aralash'), ('normal', 'Normal'), ('sensitive', 'Sezgir')], max_length=20, verbose_name='Teri turi'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=256, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='products',
            field=models.ManyToManyField(blank=True, through='users.UserProduct', to='products.product', verbose_name='Mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram username'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sotib olingan sana'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='week1_sent',
            field=models.BooleanField(default=False, verbose_name='1-hafta yuborilgan'),
        ),
        migrations.AlterField(
            model_name='userproduct',
            name='week2_sent',
            field=models.BooleanField(default=False, verbose_name='2-hafta yuborilgan'),
        ),
    ]
