# Generated by Django 5.0.4 on 2026-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramuser_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, editable=False, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
