# Generated by Django 5.0.4 on 2026-07-17 12:09

from django.db import migrations, models


def backfill(apps, schema_editor):
    """Derive the tail for customers that existed before this column."""
    TelegramUser = apps.get_model("users", "TelegramUser")
    updates = []
    for user in TelegramUser.objects.exclude(phone_number="").iterator():
        digits = "".join(ch for ch in user.phone_number if ch.isdigit())
        user.phone_tail = digits[-9:] if len(digits) >= 9 else ""
        updates.append(user)
    TelegramUser.objects.bulk_update(updates, ["phone_tail"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='phone_tail',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=9),
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
