# Generated by Django 5.0.4 on 2026-07-17 12:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0007_telegramuser_phone_tail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='sellerprofile',
            options={'verbose_name': 'Sotuvchi sozlamasi', 'verbose_name_plural': 'Sotuvchi sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Xaridor', 'verbose_name_plural': 'Xaridorlar'},
        ),
        migrations.AlterModelOptions(
            name='userproduct',
            options={'verbose_name': 'Sotib olingan mahsulot', 'verbose_name_plural': 'Sotib olingan mahsulotlar'},
        ),
    ]
