# Generated by Django 5.0.4 on 2026-07-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fix_seller_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='source',
            field=models.CharField(choices=[('self', "O'zi ro'yxatdan o'tgan"), ('admin', 'Admin yordamida'), ('app', 'Mobil ilova')], default='self', max_length=10),
        ),
    ]
