# Generated by Django 5.0.4 on 2026-07-20 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_telegramuser_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
            ],
            options={
                'verbose_name': 'App foydalanuvchisi',
                'verbose_name_plural': 'App foydalanuvchilari',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.telegramuser',),
        ),
    ]
