# Generated by Django 5.0.4 on 2026-07-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_seller_app_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', help_text='Mijoz botda tanlagan til. Xabarlar shu tilda yuboriladi.', max_length=5, verbose_name='Til'),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='registered_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name="Ro'yxatdan o'tgan vaqt"),
        ),
    ]
