# Generated by Django 5.0.4 on 2026-07-28 08:23

import apps.users.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_backfill_registered_at_and_seller_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLoginSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.users.models._generate_login_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=apps.users.models._default_login_session_expiry)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Ilova kirish sessiyasi',
                'verbose_name_plural': 'Ilova kirish sessiyalari',
            },
        ),
    ]
