# Generated by Django 5.0.4 on 2026-07-17 12:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_alter_telegramuser_telegram_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Foydalanuvchining birinchi xabaridan avtomatik olinadi.', max_length=128, verbose_name='Mavzu')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('answered', 'Javob berildi'), ('closed', 'Yopilgan')], db_index=True, default='new', max_length=16, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan vaqt')),
                ('last_message_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Oxirgi xabar')),
                ('awaiting_reply', models.BooleanField(db_index=True, default=True, verbose_name='Javob kutilmoqda')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to='users.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-awaiting_reply', '-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Foydalanuvchidan'), ('out', 'Admindan')], max_length=4, verbose_name="Yo'nalish")),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('photo_file_id', models.CharField(blank=True, editable=False, max_length=512)),
                ('delivered', models.BooleanField(default=True, editable=False, verbose_name='Yetkazildi')),
                ('error_detail', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vaqt')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportthread', verbose_name='Murojaat')),
            ],
            options={
                'verbose_name': 'Murojaat xabari',
                'verbose_name_plural': 'Murojaat xabarlari',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['-last_message_at'], name='support_sup_last_me_af1563_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', '-last_message_at'], name='support_sup_status_815488_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'created_at'], name='support_sup_thread__887d25_idx'),
        ),
    ]
