# Generated by Django 5.0.4 on 2026-07-22 07:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _copy_photo_file_id(apps, schema_editor):
    """Preserve existing photo attachments under the new generic field."""
    SupportMessage = apps.get_model('support', 'SupportMessage')
    SupportMessage.objects.filter(photo_file_id__gt='').update(
        attachment_file_id=models.F('photo_file_id'), attachment_type='photo'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Telegram ID')),
                ('name', models.CharField(blank=True, help_text="Ixtiyoriy — bo'sh qoldirsangiz, birinchi javobdan avtomatik olinadi.", max_length=128, verbose_name='Ism')),
                ('enabled', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan sana")),
            ],
            options={
                'verbose_name': 'Guruh admini',
                'verbose_name_plural': 'Guruh adminlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_chat_id', models.BigIntegerField(blank=True, help_text="Support xabarlari shu guruhga yuboriladi. Botni guruhga qo'shib, guruh ID sini shu yerga kiriting.", null=True, verbose_name='Guruh Chat ID')),
                ('connection_status', models.CharField(choices=[('unknown', 'Tekshirilmagan'), ('ok', 'Ulangan'), ('error', 'Xatolik')], default='unknown', editable=False, max_length=8, verbose_name='Ulanish holati')),
                ('last_checked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Oxirgi tekshiruv')),
                ('last_error', models.TextField(blank=True, editable=False, verbose_name='Xato')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram guruh sozlamasi',
                'verbose_name_plural': 'Telegram guruh sozlamasi',
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachment_file_id',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='attachment_type',
            field=models.CharField(blank=True, choices=[('photo', 'Rasm'), ('document', 'Hujjat'), ('voice', 'Ovozli xabar'), ('video', 'Video'), ('sticker', 'Stiker')], editable=False, max_length=16),
        ),
        migrations.RunPython(_copy_photo_file_id, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='supportmessage',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='photo_file_id',
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='group_chat_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='group_message_id',
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='retry_count',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='status',
            field=models.CharField(choices=[('sent', 'Yuborildi'), ('failed', 'Yuborilmadi')], default='sent', editable=False, max_length=8, verbose_name='Holat'),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='telegram_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='support.supportadmin', verbose_name='Telegram admin'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['group_chat_id', 'group_message_id'], name='support_sup_group_c_e0a3c4_idx'),
        ),
    ]
