# Generated by Django 5.0.4 on 2026-07-13 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('start', 'Bot started'), ('registered', 'Registration completed'), ('tutorial_view', 'Tutorial step viewed'), ('feedback', 'Feedback submitted'), ('progress', 'Progress photos submitted')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Bot event',
                'verbose_name_plural': 'Bot events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='progress_photos/')),
                ('label', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=8)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'Progress photo',
                'verbose_name_plural': 'Progress photos',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'User feedback',
                'verbose_name_plural': 'User feedback',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
