# Generated by Django 5.0.4 on 2026-07-16 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('users', '0004_fix_group_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bot hodisasi', 'verbose_name_plural': 'Bot hodisalari'},
        ),
        migrations.AlterModelOptions(
            name='progressphoto',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Natija rasmi', 'verbose_name_plural': 'Natija rasmlari'},
        ),
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Foydalanuvchi fikri', 'verbose_name_plural': 'Foydalanuvchi fikrlari'},
        ),
        migrations.CreateModel(
            name='AiMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI konsultant')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_messages', to='users.telegramuser')),
            ],
            options={
                'verbose_name': 'AI suhbat xabari',
                'verbose_name_plural': 'AI suhbatlar',
                'ordering': ['created_at'],
            },
        ),
    ]
