# Generated by Django 5.0.4 on 2026-07-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_botevent_options_alter_progressphoto_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AiMessage',
        ),
    ]
