# Generated by Django 5.0.4 on 2026-07-16 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_delete_aimessage'),
        ('products', '0002_video_alter_product_options_and_more'),
        ('users', '0004_fix_group_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='event_type',
            field=models.CharField(choices=[('start', 'Bot ishga tushirildi'), ('registered', "Ro'yxatdan o'tdi"), ('tutorial_view', "Qo'llanma ko'rildi"), ('feedback', 'Fikr yuborildi'), ('progress', 'Natija rasmlari yuborildi')], max_length=32, verbose_name='Hodisa turi'),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='payload',
            field=models.JSONField(blank=True, default=dict, verbose_name="Ma'lumot"),
        ),
        migrations.AlterField(
            model_name='botevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='label',
            field=models.CharField(choices=[('before', 'Oldin'), ('after', 'Keyin')], max_length=8, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='photo',
            field=models.ImageField(upload_to='progress_photos/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Baho (1-5)'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='text',
            field=models.TextField(blank=True, verbose_name='Fikr matni'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.telegramuser', verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='week',
            field=models.PositiveSmallIntegerField(verbose_name='Hafta'),
        ),
    ]
