# Generated by Django 5.0.4 on 2026-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_alter_botevent_created_at_alter_botevent_event_type_and_more'),
        ('products', '0003_remove_producttutorialstep_video_and_more'),
        ('users', '0006_alter_telegramuser_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botevent',
            name='user',
        ),
        migrations.RemoveField(
            model_name='progressphoto',
            name='photo',
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='file_id',
            field=models.CharField(blank=True, editable=False, max_length=512, verbose_name='Telegram file_id'),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='progress_thumbs/%Y/%m/', verbose_name='Kichik nusxa'),
        ),
        migrations.AddField(
            model_name='progressphoto',
            name='thumbnail_purged',
            field=models.BooleanField(default=False, editable=False, help_text="Thumbnail diskdan o'chirilgan; original Telegramda saqlanib qolgan.", verbose_name='Kichik nusxa tozalangan'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='admin_reply',
            field=models.TextField(blank=True, help_text='Bu yerga yozib saqlasangiz, matn botda mijozga yuboriladi.', verbose_name='Javob (mijozga yuboriladi)'),
        ),
        migrations.AddField(
            model_name='userfeedback',
            name='reply_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Javob yuborildi'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['user', '-submitted_at'], name='analytics_p_user_id_c9b646_idx'),
        ),
        migrations.AddIndex(
            model_name='progressphoto',
            index=models.Index(fields=['-submitted_at'], name='analytics_p_submitt_a0e46d_idx'),
        ),
        migrations.DeleteModel(
            name='BotEvent',
        ),
    ]
