# Generated by Django 5.0.4 on 2026-07-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_remove_botevent_user_remove_progressphoto_photo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedback',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Fikr', 'verbose_name_plural': 'Fikrlar'},
        ),
    ]
