# Generated by Django 5.0.4 on 2026-07-23 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_alter_userfeedback_options'),
        ('users', '0013_telegramuser_language_telegramuser_registered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinQuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=20, verbose_name='Aniqlangan teri turi')),
                ('answers', models.JSONField(default=dict, verbose_name='Javoblar')),
                ('recommendation_keys', models.JSONField(default=list, verbose_name='Berilgan tavsiyalar')),
                ('language', models.CharField(default='uz', max_length=5, verbose_name='Til')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Topshirilgan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_quiz_results', to='users.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Teri testi natijasi',
                'verbose_name_plural': 'Teri testi natijalari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_s_user_id_56d3af_idx')],
            },
        ),
    ]
