# Generated by Django 5.0.4 on 2026-07-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_skinquizresult'),
        ('users', '0015_telegramloginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceAnalysisPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_type', models.CharField(max_length=20, verbose_name='Teri turi')),
                ('image', models.ImageField(upload_to='face_analysis/', verbose_name='Rasm')),
                ('filename', models.CharField(editable=False, max_length=255, verbose_name='Fayl nomi')),
                ('synced_to_sheet', models.BooleanField(default=False, editable=False, verbose_name='Sheetga yozildi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_analysis_photos', to='users.telegramuser', verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Yuz tahlili rasmi',
                'verbose_name_plural': 'Yuz tahlili rasmlari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_f_user_id_7860ff_idx')],
            },
        ),
    ]
