# Generated by Django 5.0.4 on 2026-09-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0015_telegramloginsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Katta-kichik harf va tirelar ahamiyatsiz — mijoz qanday yozsa ham topiladi.', max_length=32, unique=True, verbose_name="Kalit so'z")),
                ('label', models.CharField(blank=True, help_text="O'zingiz uchun: bu kalit kimga berilgani, masalan «Sentabr aksiyasi».", max_length=120, verbose_name='Izoh')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 — cheksiz. 1 — faqat bitta mijoz ishlatadi.', verbose_name='Nechta mijozga')),
                ('uses_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Ishlatilgan')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Bo'sh qoldirsangiz — muddatsiz.", null=True, verbose_name='Amal qilish muddati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': "Kalit so'z",
                'verbose_name_plural': "Kalit so'zlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Mijoz ko'radigan sarlavha, masalan: «Terini to'g'ri tozalash».", max_length=120, verbose_name='Nomi')),
                ('title_ru', models.CharField(blank=True, max_length=120, verbose_name='Nomi (ruscha)')),
                ('title_en', models.CharField(blank=True, max_length=120, verbose_name='Nomi (inglizcha)')),
                ('description', models.TextField(blank=True, help_text="Ixtiyoriy. Ro'yxatda sarlavha ostida ko'rinadi.", verbose_name='Qisqa izoh')),
                ('description_ru', models.TextField(blank=True, verbose_name='Qisqa izoh (ruscha)')),
                ('description_en', models.TextField(blank=True, verbose_name='Qisqa izoh (inglizcha)')),
                ('order', models.PositiveSmallIntegerField(default=1, help_text='Kichik raqam yuqorida turadi: 1, 2, 3 …', verbose_name='Tartib')),
                ('video_file', models.FileField(blank=True, help_text='MP4 tavsiya qilinadi. Telegram bitta faylga 50 MB ruxsat beradi.', upload_to='lessons/', verbose_name='Video fayl')),
                ('video_file_id', models.CharField(blank=True, help_text="Birinchi yuborishdan keyin bot o'zi to'ldiradi. Boshqa botdan ko'chirayotgan bo'lsangiz qo'lda ham kiritishingiz mumkin.", max_length=512, verbose_name='Telegram video ID')),
                ('duration_seconds', models.PositiveIntegerField(default=0, editable=False, verbose_name='Davomiyligi (soniya)')),
                ('is_active', models.BooleanField(default=True, help_text="Belgi olib tashlansa dars ro'yxatdan yo'qoladi.", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan")),
            ],
            options={
                'verbose_name': 'Video dars',
                'verbose_name_plural': 'Video darslar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LessonUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Ochilgan vaqt')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='lessons.accesscode', verbose_name='Ishlatilgan kalit')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_unlock', to='users.telegramuser', verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Ochilgan dars',
                'verbose_name_plural': 'Kim darslarni ochgan',
                'ordering': ['-unlocked_at'],
            },
        ),
    ]
