# Generated by Django 5.0.4 on 2026-09-10 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('users', '0015_telegramloginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesscode',
            name='issued_to',
            field=models.ForeignKey(blank=True, help_text="Ixtiyoriy: xaridorni tanlab qo'ysangiz, kimga qaysi kod berilgani keyin ham ma'lum bo'ladi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_codes', to='users.telegramuser', verbose_name='Kimga berilgan'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='1 — faqat bitta mijoz ishlatadi (tavsiya etiladi). 0 — cheksiz, butun aksiya uchun.', verbose_name='Nechta mijozga'),
        ),
    ]
