# Generated by Django 5.0.4 on 2026-09-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_accesscode_issued_to_alter_accesscode_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonvideo',
            name='poster',
            field=models.ImageField(blank=True, help_text="Bo'sh qoldirsangiz videodan avtomatik olinadi. Yoqmasa o'z rasmingizni yuklang.", upload_to='lessons/posters/', verbose_name='Muqova rasmi'),
        ),
    ]
